version: '3.9'

services:

    app:
        build:
            context: .
        # デバッグのため、Dockerfileのentrypointが記載されていない、docker-composeで起動
        command: python ./main.py
        volumes:
            - .:/code
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: db
            POSTGRES_PORT: 5432
            POSTGRES_DB: ${POSTGRES_DB}
            RELOAD: "True"
        depends_on:
          - db

    db:
        image: postgres:13.3-alpine
        volumes:
            - ${PWD}/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ${PWD}/data/db:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_INITDB_ARGS: --encoding=UTF-8
        ports:
            - "54320:5432"
